export const teamRosters: Record<string, string[]> = {
  "Casey": [
    "Adam Jemal",
    "Angus Walker",
    "Ibrahim Gebre",
    "Isaac Campbell",
    "Kai Ivy Jr",
    "Kobe Romano",
    "Malachi Singh",
    "Mason Green",
    "Ved Suthar",
    "Yusuf Collins",
  ],
  "Dandenong": [
    "Abdi Abdu",
    "Ahmed Green",
    "Archer King",
    "Hamza Martin",
    "Jaxon Phillips",
    "Kobe Green",
    "Latoya Williams",
    "Matías Romero",
    "Oscar Morris",
    "Tyler Anderson",
  ],
  "Knox": [
    "Bailey Martin",
    "Caleb Hill",
    "Daniel Wright",
    "Emmanuel Robinson",
    "Henry Miller",
    "Joel Parker",
    "Joel Sato",
    "Nate Evans",
    "Steven Morehu",
    "Thabo Ngcobo",
  ],
  "Bulleen": [
    "Benjamin Jones",
    "David Wilson",
    "Elias Bekele",
    "Ibrahim Ndlovu",
    "Jayden Stewart",
    "Jordan Bekele",
    "Lucas Williams",
    "Omar Mokoena",
    "Richard Ponzi",
    "Theo Ndlovu",
  ],
  "Frankston": [
    "Alexander Lopez",
    "Dwayne Smith",
    "Emmanuel Evans",
    "Ethan Hill",
    "James Williams",
    "Joel Hill",
    "Joseph Jackson",
    "Levi Taylor",
    "Noah Chen",
    "Samuel Carter",
  ],
  "Kilsyth": [
    "Angus Tanaka",
    "Dylan Nguyen",
    "Elias White",
    "Henry Lopez",
    "Henry Parker",
    "Logan Smith",
    "Micah Green",
    "Mohinder Singh",
    "Sebastian Green",
    "Sebastian Singh",
  ],
  "Eltham": [
    "Angus Green",
    "Archer Carter",
    "Benjamin Lopez",
    "David Lee",
    "Elijah Singh",
    "Hamza Turner",
    "Joseph Campbell",
    "Lachlan Murphy",
    "Liam Brown",
    "Max Turner",
  ],
  "Keilor": [
    "Bailey Ali",
    "Franco Delgado",
    "Hamish Sato",
    "Jack Dawson",
    "Jayden Lee",
    "Jayden Phillips",
    "Levi Anderson",
    "Levi Mohamed",
    "Noah Patel",
    "Santiago Gómez",
  ],
  "Nunawading": [
    "Aiden Parker",
    "Bruno Fernández",
    "Hudson Ahmed",
    "Iván Cabrera",
    "Jayden Baker",
    "Riley Wilson",
    "Samuel Tesfaye",
    "Sebastian Brown",
    "Thomas Mokoena",
    "Tyler Nguyen",
  ],
  "McKinnon": [
    "Ahmed Wilson",
    "Alexander Brown",
    "Benjamin Lee",
    "Caleb Jones",
    "Daniel Lopez",
    "Ethan Turner",
    "James Carter",
    "Joseph Miller",
    "Levi Martin",
    "Noah Anderson",
  ],
  "Diamond Valley": [
    "Aiden Smith",
    "Angus Campbell",
    "Archer Evans",
    "Bailey Green",
    "Benjamin Parker",
    "Dylan Wilson",
    "Elias Martin",
    "Hamish Jones",
    "Jack Brown",
    "Jayden Lee",
  ],
  "Waverley": [
    "Alexander Hill",
    "Caleb Taylor",
    "Daniel Chen",
    "Emmanuel Ali",
    "Ethan Baker",
    "James Ahmed",
    "Joel Nguyen",
    "Joseph Patel",
    "Levi Singh",
    "Noah Sato",
  ],
  "Sandringham": [
    "Aiden Carter",
    "Angus Miller",
    "Archer Anderson",
    "Bailey Martin",
    "Benjamin Turner",
    "Dylan Lopez",
    "Elias Green",
    "Hamish Parker",
    "Jack Wilson",
    "Jayden Brown",
  ],
  "Altona": [
    "Alexander Evans",
    "Caleb Campbell",
    "Daniel Jones",
    "Emmanuel Lee",
    "Ethan Smith",
    "James Taylor",
    "Joel Chen",
    "Joseph Ali",
    "Levi Baker",
    "Noah Ahmed",
  ],
  "Geelong": [
    "Aiden Nguyen",
    "Angus Patel",
    "Archer Singh",
    "Bailey Sato",
    "Benjamin Carter",
    "Dylan Miller",
    "Elias Anderson",
    "Hamish Martin",
    "Jack Turner",
    "Jayden Lopez",
  ],
  "Bendigo": [
    "Alexander Green",
    "Caleb Parker",
    "Daniel Wilson",
    "Emmanuel Brown",
    "Ethan Evans",
    "James Campbell",
    "Joel Jones",
    "Joseph Lee",
    "Levi Smith",
    "Noah Taylor",
  ],
  "Ballarat": [
    "Aiden Chen",
    "Angus Ali",
    "Archer Baker",
    "Bailey Ahmed",
    "Benjamin Nguyen",
    "Dylan Patel",
    "Elias Singh",
    "Hamish Sato",
    "Jack Carter",
    "Jayden Miller",
  ],
  "Pakenham": [
    "Alexander Anderson",
    "Caleb Martin",
    "Daniel Turner",
    "Emmanuel Lopez",
    "Ethan Green",
    "James Parker",
    "Joel Wilson",
    "Joseph Brown",
    "Levi Evans",
    "Noah Campbell",
  ],
  "Wyndham": [
    "Aiden Jones",
    "Angus Lee",
    "Archer Smith",
    "Bailey Taylor",
    "Benjamin Chen",
    "Dylan Ali",
    "Elias Baker",
    "Hamish Ahmed",
    "Jack Nguyen",
    "Jayden Patel",
  ],
  "Sunbury": [
    "Alexander Singh",
    "Caleb Sato",
    "Daniel Carter",
    "Emmanuel Miller",
    "Ethan Anderson",
    "James Martin",
    "Joel Turner",
    "Joseph Lopez",
    "Levi Green",
    "Noah Parker",
  ],
  "Melbourne": [
    "Aiden Wilson",
    "Angus Brown",
    "Archer Evans",
    "Bailey Campbell",
    "Benjamin Jones",
    "Dylan Lee",
    "Elias Smith",
    "Hamish Taylor",
    "Jack Chen",
    "Jayden Ali",
  ],
  "Whittlesea": [
    "Alexander Baker",
    "Caleb Ahmed",
    "Daniel Nguyen",
    "Emmanuel Patel",
    "Ethan Singh",
    "James Sato",
    "Joel Carter",
    "Joseph Miller",
    "Levi Anderson",
    "Noah Martin",
  ],
  "Wangaratta": [
    "Aiden Turner",
    "Angus Lopez",
    "Archer Green",
    "Bailey Parker",
    "Benjamin Wilson",
    "Dylan Brown",
    "Elias Evans",
    "Hamish Campbell",
    "Jack Jones",
    "Jayden Lee",
  ],
  "Broadmeadows": [
    "Alexander Smith",
    "Caleb Taylor",
    "Daniel Chen",
    "Emmanuel Ali",
    "Ethan Baker",
    "James Ahmed",
    "Joel Nguyen",
    "Joseph Patel",
    "Max Williams",
    "Omar Sato",
  ],
};

export const teamCoaches: Record<string, string> = {
  "Casey": "Julian Vickerman",
  "Dandenong": "Corey Bradler",
};