export const teamRosters: Record<string, string[]> = {
  "Casey": [
    "Adam Jemal",
    "Angus Walker",
    "Ibrahim Gebre",
    "Isaac Campbell",
    "Kai Ivy Jr",
    "Kobe Romano",
    "Malachi Singh",
    "Mason Green",
    "Private Player",
    "Yusuf Collins",
  ],
  "Dandenong": [
    "Abdi Abdu",
    "Ahmed Green",
    "Archer King",
    "Hamza Martin",
    "Jaxon Phillips",
    "Kobe Green",
    "Latoya Williams",
    "Matías Romero",
    "Oscar Morris",
    "Tyler Anderson",
  ],
  "Knox": [
    "Bailey Martin",
    "Caleb Hill",
    "Daniel Wright",
    "Emmanuel Robinson",
    "Henry Miller",
    "Joel Parker",
    "Joel Sato",
    "Nate Evans",
    "Steven Morehu",
    "Thabo Ngcobo",
  ],
  "Bulleen": [
    "Benjamin Jones",
    "David Wilson",
    "Elias Bekele",
    "Ibrahim Ndlovu",
    "Jayden Stewart",
    "Jordan Bekele",
    "Lucas Williams",
    "Omar Mokoena",
    "Richard Ponzi",
    "Theo Ndlovu",
  ],
  "Frankston": [
    "Alexander Lopez",
    "Dwayne Smith",
    "Emmanuel Evans",
    "Ethan Hill",
    "James Williams",
    "Joel Hill",
    "Joseph Jackson",
    "Levi Taylor",
    "Noah Chen",
    "Samuel Carter",
  ],
  "Kilsyth": [
    "Angus Tanaka",
    "Dylan Nguyen",
    "Elias White",
    "Henry Lopez",
    "Henry Parker",
    "Logan Smith",
    "Micah Green",
    "Mohinder Singh",
    "Sebastian Green",
    "Sebastian Singh",
  ],
  "Eltham": [
    "Angus Green",
    "Archer Carter",
    "Benjamin Lopez",
    "David Lee",
    "Elijah Singh",
    "Hamza Turner",
    "Joseph Campbell",
    "Lachlan Murphy",
    "Liam Brown",
    "Max Turner",
  ],
  "Keilor": [
    "Bailey Ali",
    "Franco Delgado",
    "Hamish Sato",
    "Jack Dawson",
    "Jayden Lee",
    "Jayden Phillips",
    "Levi Anderson",
    "Levi Mohamed",
    "Noah Patel",
    "Santiago Gómez",
  ],
  "Nunawading": [
    "Aiden Parker",
    "Bruno Fernández",
    "Hudson Ahmed",
    "Iván Cabrera",
    "Jayden Baker",
    "Riley Wilson",
    "Samuel Tesfaye",
    "Sebastian Collins",
    "Tomás Alvarez",
    "Tyler Baker",
  ],
  "McKinnon": [
    "Benjamin Davis",
    "Henry Evans",
    "Jordan Mitchell",
    "Levi Adams",
    "Logan Miller",
    "Max Walker",
    "Riley Harris",
    "Tyrone Smith",
    "Xavier Evans",
    "Xavier Mokoena",
  ],
  "Diamond Valley": [
    "Abel Kiran",
    "Ahmed Baker",
    "Finn Campbell",
    "Ishan Yadav",
    "Lucas Jones",
    "Max Lee",
    "Micah Tran",
    "Sebastian Parker",
    "Theo Campbell",
    "Yusuf Wright",
  ],
  "Waverley": [
    "Ben Botic",
    "Harvey Tran",
    "Hudson Clark",
    "Hudson Stewart",
    "Jack Brown",
    "James Brown",
    "Leo Williams",
    "Mason Garcia",
    "Max Kumar",
    "Theo Evans",
  ],
  "Sandringham": [
    "Bailey Gebre",
    "Brock Martin",
    "Hamza Anderson",
    "Harvey Moretti",
    "James Johnson",
    "Jayden Tesfaye",
    "Joseph Clark",
    "Levi Baker",
    "Lincoln Haddad",
    "Noah Romano",
  ],
  "Altona": [
    "Ahmed Ali",
    "Caleb Young",
    "Dwayne Thompson",
    "Elias Collins",
    "Isaac Bekele",
    "Julián Herrera",
    "Levi King",
    "Lucas Hill",
    "Mason Smith",
    "Riley Ndlovu",
  ],
  "Geelong": [
    "Archer Kim",
    "Caleb Mensah",
    "Hudson Abebe",
    "Hunter Wilson",
    "Kagiso Nkosi",
    "Malachi White",
    "Marcus Romano",
    "Mason Jones",
    "Nathan Taylor",
    "Oscar Evans",
  ],
  "Bendigo": [
    "Angus Moretti",
    "Aoi Sato",
    "David Mensah",
    "Elias Turner",
    "Ethan Kumar",
    "Jack Patel",
    "Joseph King",
    "Michael Makena",
    "Samuel Mitchell",
    "Souta Watanabe",
  ],
  "Ballarat": [
    "Cooper Ndlovu",
    "Elijah Nelson",
    "Haruto Watanabe",
    "Isaac Turner",
    "Lucas King",
    "Lucas Okafor",
    "Mason Zhang",
    "Oscar Scott",
    "Thabo Khumalo",
    "Yui Suzuki",
  ],
  "Pakenham": [
    "Angus Chen",
    "Bhav Sharma",
    "Elijah Sharma",
    "Ethan Green",
    "Finn Morris",
    "Liam Gonzalez",
    "Liam Gonzalez",
    "Rav Krishna",
    "Tyler Edwards",
    "Zane Okafor",
  ],
  "Wyndham": [
    "Isaac Wilson",
    "Khoder Brown",
    "Leo Walker",
    "Mark Rogers",
    "Mason Evans",
    "Noah Edwards",
    "Noah Garcia",
    "Omar Bekele",
    "Samuel Hill",
    "Theo Williams",
  ],
  "Sunbury": [
    "Ahmed Turner",
    "Dylan Kumar",
    "Elias Tesfaye",
    "Elijah Gebre",
    "Henry Johnson",
    "Levi Williams",
    "Liam Miller",
    "Noah Gonzalez",
    "Samuel Mokoena",
    "Xavier Moretti",
  ],
  "Melbourne": [
    "Alex Tran",
    "Alexander Miller",
    "Bailey Young",
    "Bilal Gebre",
    "Elias Romano",
    "Emmanuel Moretti",
    "Henry Mohamed",
    "Jack Jones",
    "Marcus Abebe",
    "Samuel Nelson",
  ],
  "Whittlesea": [
    "Aaarav Patel",
    "Harvey Thomas",
    "Hudson Baker",
    "Joshua Sharma",
    "Liam Smith",
    "Liam Taylor",
    "Malachi Ahmed",
    "Mason Mokoena",
    "Sebastian Adams",
    "Tyler Martin",
  ],
  "Wangaratta": [
    "Elias Campbell",
    "Jaxon Edwards",
    "Joel Chen",
    "Joel Mitchell",
    "Logan Johnson",
    "Max Hassan",
    "Omar Stewart",
    "Ren Suzuki",
    "Theo Collins",
    "Xavier Lee",
  ],
  "Broadmeadows": [
    "Aiden King",
    "Bailey Edwards",
    "Elijah Phillips",
    "Joel Williams",
    "Jordan Martin",
    "Latoya Thompson",
    "Lautaro Sánchez",
    "Mason Walker",
    "Max Williams",
    "Omar Sato",
  ],
};

export const teamCoaches: Record<string, string> = {
  "Casey": "Julian Vickerman",
  "Dandenong": "Corey Bradler",
};
